### ISSUE TITLE
Errors in Hadoop HDFS TestFsDatasetCache test timed out

### ISSUE THREAD

**Issue by jdivyasree** [OpenPOWER-BigData/HDP2.5-hadoop#3]
Results :

Tests in error:
TestFsDatasetCache.testPageRounder:472 ? test timed out after 60000 milliseco...
TestFsDatasetCache.tearDown:149 ? Timeout Timed out waiting for condition. Thr...
TestFsDatasetCache.testUncachingBlocksBeforeCachingFinishes:422 ? Timeout Time...
TestFsDatasetCache.tearDown:149 ? Timeout Timed out waiting for condition. Thr...
TestFsDatasetCache.testCacheAndUncacheBlockSimple:288->testCacheAndUncacheBlock:261 ? Timeout
TestFsDatasetCache.tearDown:149 ? Timeout Timed out waiting for condition. Thr...
TestFsDatasetCache.testFilesExceedMaxLockedMemory:346 ? Timeout Timed out wait...
TestFsDatasetCache.tearDown:149 ? Timeout Timed out waiting for condition. Thr...
TestFsDatasetCache.testCacheAndUncacheBlockWithRetries:315->testCacheAndUncacheBlock:261 ? Timeout
TestFsDatasetCache.tearDown:149 ? Timeout Timed out waiting for condition. Thr...

Tests run: 13, Failures: 0, Errors: 10, Skipped: 0

**Comment by yussufsh** [comment]
https://github.com/OpenPOWER-BigData/HDP-Hadoop/issues/2
